version: '3.3'
services:
  postgresql:
    image: postgres:12.18-bullseye
    environment:
      POSTGRES_DATABASE: testdb
      POSTGRES_PASSWORD: passw0rd
    volumes:
    - ./postgres/scripts:/scripts
  fluentd:
    build:
      context: fluentd
    # image: fluentd:1.0.0
    init: true
    working_dir: /fluentd
    volumes:
    - ./fluentd/etc:/fluentd/etc
    - ./data/fluentd:/data
    # command: bash -c "while true; do sleep 30; done"
