helmDefaults:
  createNamespace: true

repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
releases:
- name: postgresql
  namespace: postgresql
  chart: bitnami/postgresql
  version: 14.2.3
- name: fluentd
  namespace: postgresql
  chart: bitnami/fluentd
  version: 5.17.2

